(load "node2leaves1.clp")
(load-facts "node2leaves1.dat")
(load-facts "word.dat")
(facts)
(watch activations)
(watch facts)
(run)
(facts)
(save-facts "E-chunk_ids.dat"  local Ancestor-Successors_id )
;(save-facts "E-chunks-words.dat"  local Ancestor-Head-Successors_word)
(save-facts "E-ancestor-successor.dat" local Head-Level-Successor_depth-Ancestor-Successor)
(exit)
